name: qcarchive-docs
channels:
    - conda-forge
dependencies:
    - python=3
    - sphinx
    - sphinx_rtd_theme
    - nbconvert
    - nbsphinx >=0.5
    - nbformat
    - pandoc
    - pygments
    - jupyter_client
    - ipython
    - pip

      # Depends
    - qcportal
